/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-11-29 02:53:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.lava.lavafaq.bean.Person;
import java.util.*;

public final class addConference_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-cn\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<!-- Title and other stuffs -->\r\n");
      out.write("<title>个人资料</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"个人资料\" />\r\n");
      out.write("<meta name=\"description\" content=\"个人资料\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<!-- Stylesheets -->\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/pages/style/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Font awesome icon -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/font-awesome.css\">\r\n");
      out.write("<!-- jQuery UI -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/jquery-ui.css\">\r\n");
      out.write("<!-- Calendar -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/fullcalendar.css\">\r\n");
      out.write("<!-- prettyPhoto -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/prettyPhoto.css\">\r\n");
      out.write("<!-- Star rating -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/rateit.css\">\r\n");
      out.write("<!-- Date picker -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(path);
      out.write("/pages/style/bootstrap-datetimepicker.min.css\">\r\n");
      out.write("<!-- CLEditor -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/jquery.cleditor.css\">\r\n");
      out.write("<!-- Uniform -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/uniform.default.css\">\r\n");
      out.write("<!-- Bootstrap toggle -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/bootstrap-switch.css\">\r\n");
      out.write("<!-- Main stylesheet -->\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/pages/style/style2.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Widgets stylesheet -->\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/pages/style/widgets.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 Support for IE -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("\t  <script src=\"js/html5shim.js\"></script>\r\n");
      out.write("\t  <![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(path);
      out.write("/pages/img/favicon/favicon.png\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		Person user = (Person) request.getSession().getAttribute("user");
	
      out.write("\r\n");
      out.write("\t<input type=\"hidden\" id=\"id\" value=\"");
      out.print(user.getId());
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Main bar -->\r\n");
      out.write("\t\t<div class=\"mainbar\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Page heading -->\r\n");
      out.write("\t\t\t<div class=\"page-head\">\r\n");
      out.write("\t\t\t\t<!-- Page heading -->\r\n");
      out.write("\t\t\t\t<!-- page meta -->\r\n");
      out.write("\t\t\t\t<span class=\"page-meta\">添加会议室</span>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Breadcrumb -->\r\n");
      out.write("\t\t\t\t<div class=\"bread-crumb pull-right\">\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(basePath);
      out.write("pages/main/admin\"><i class=\"icon-home\"></i>\r\n");
      out.write("\t\t\t\t\t\tHome</a>\r\n");
      out.write("\t\t\t\t\t<!-- Divider -->\r\n");
      out.write("\t\t\t\t\t<span class=\"divider\">/</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Page heading ends -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Matter -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"matter\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"widget wgreen\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-head\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pull-left\">添加会议室</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"widget-icons pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"wminimize\"><i class=\"icon-chevron-up\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"wclose\"><i class=\"icon-remove\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"padd\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- Form starts.  -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form class=\"form-horizontal\" role=\"form\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-lg-4 control-label\">会议室名称</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"crmname\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"请输入会议室名称\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-lg-1 control-label\"> 会议室地址</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"crmaddress\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"请输入会议室地址\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-lg-1 control-label\"> 容纳人数</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"holdnum\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"请输入容纳人数\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-lg-3 control-label\">是否多媒体</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label> <input type=\"radio\" name=\"optionsRadios\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"optionsRadios1\" value=\"1\" checked> 是\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label> <input type=\"radio\" name=\"optionsRadios\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"optionsRadios2\" value=\"0\"> 否\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-offset-1 col-lg-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button id=\"save\" type=\"button\" class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#myModal\">保存设置</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-foot\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Footer goes here -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Matter ends -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Mainbar ends -->\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\t\taria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">添加会议室</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">确定添加会议室吗？</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"updateperson\">提交</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.modal-content -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.modal -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Content ends -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer starts -->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<!-- Copyright info -->\r\n");
      out.write("\t\t\t\t\t<p class=\"copy\">\r\n");
      out.write("\t\t\t\t\t\tCopyright &copy; 2018 | <a href=\"#\">yufu</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer ends -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scroll to top -->\r\n");
      out.write("\t<span class=\"totop\"><a href=\"#\"><i class=\"icon-chevron-up\"></i></a></span>\r\n");
      out.write("\r\n");
      out.write("\t<!-- JS -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.js\"></script>\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/bootstrap.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery-ui-1.9.2.custom.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery UI -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/fullcalendar.min.js\"></script>\r\n");
      out.write("\t<!-- Full Google Calendar - Calendar -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.rateit.min.js\"></script>\r\n");
      out.write("\t<!-- RateIt - Star rating -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.prettyPhoto.js\"></script>\r\n");
      out.write("\t<!-- prettyPhoto -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery Flot -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/excanvas.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.flot.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.flot.resize.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.flot.pie.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.flot.stack.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery Notification - Noty -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.noty.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/themes/default.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/layouts/bottom.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/layouts/topRight.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/layouts/top.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<!-- jQuery Notification ends -->\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/sparklines.js\"></script>\r\n");
      out.write("\t<!-- Sparklines -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.cleditor.min.js\"></script>\r\n");
      out.write("\t<!-- CLEditor -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("\t<!-- Date picker -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.uniform.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery Uniform -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/bootstrap-switch.min.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap Toggle -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/filter.js\"></script>\r\n");
      out.write("\t<!-- Filter for support page -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/custom.js\"></script>\r\n");
      out.write("\t<!-- Custom codes -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/charts.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/currency.js\"></script>\r\n");
      out.write("\t<!-- Charts & Graphs -->\r\n");
      out.write("\t<script type=\"text/javascript\" language=\"javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('#save').click(function() {\r\n");
      out.write("\t\t\t\tif ($('#crmname').val() == \"\") {\r\n");
      out.write("\t\t\t\t\t$('#crmname').focus().css({\r\n");
      out.write("\t\t\t\t\t\tborder : \"1px solid red\",\r\n");
      out.write("\t\t\t\t\t\tboxShadow : \"0 0 2px red\"\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\talert(\"会议室名称不能为空\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif ($('#crmaddress').val() == \"\") {\r\n");
      out.write("\t\t\t\t\t$('#crmaddress').focus().css({\r\n");
      out.write("\t\t\t\t\t\tborder : \"1px solid red\",\r\n");
      out.write("\t\t\t\t\t\tboxShadow : \"0 0 2px red\"\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\talert(\"地址不能为空\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif ($('#holdnum').val() == \"\") {\r\n");
      out.write("\t\t\t\t\t$('#holdnum').focus().css({\r\n");
      out.write("\t\t\t\t\t\tborder : \"1px solid red\",\r\n");
      out.write("\t\t\t\t\t\tboxShadow : \"0 0 2px red\"\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\talert(\"人数不能为空\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#updateperson').click(function() {\r\n");
      out.write("\t\t\t\tvar val = $('input[name=\"optionsRadios\"]:checked').val();\r\n");
      out.write("\t\t\t\tsendData = {\r\n");
      out.write("\t\t\t\t\tcrmname : $('#crmname').val(),\r\n");
      out.write("\t\t\t\t\tcrmaddress : $('#crmaddress').val(),\r\n");
      out.write("\t\t\t\t\tmedia : val,\r\n");
      out.write("\t\t\t\t\tholdnum : $('#holdnum').val()\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\turl : \"/lavaFAQ/pages/con/addroom\",\r\n");
      out.write("\t\t\t\t\tdata : sendData,\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result.success) {\r\n");
      out.write("\t\t\t\t\t\t\t/*$('#user').focus().css({\r\n");
      out.write("\t\t\t\t\t\t\t\tborder: \"1px solid green\",\r\n");
      out.write("\t\t\t\t\t\t\t\tboxShadow: \"0 0 2px green\"\r\n");
      out.write("\t\t\t\t\t\t\t});*/\r\n");
      out.write("\t\t\t\t\t\t\talert(result.text);\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.reload();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$('#myModal').modal('hide');\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t/*$('#user').css({\r\n");
      out.write("\t\t\t\t\t\t\t\tborder: \"1px solid #D7D7D7\",\r\n");
      out.write("\t\t\t\t\t\t\t\tboxShadow: \"none\"\r\n");
      out.write("\t\t\t\t\t\t\t});*/\r\n");
      out.write("\t\t\t\t\t\t\talert(result.text);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
