/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-11-29 02:47:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.lava.lavafaq.bean.Conference;
import java.util.*;

public final class checkConferenceUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-cn\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<!-- Title and other stuffs -->\r\n");
      out.write("<title>查看会议室</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"Bootstrap后台管理系统\" />\r\n");
      out.write("<meta name=\"description\" content=\"Bootstrap后台管理系统\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/pages/css/bootstrap.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("<!-- Stylesheets -->\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/pages/style/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Font awesome icon -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/font-awesome.css\">\r\n");
      out.write("<!-- jQuery UI -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/jquery-ui.css\">\r\n");
      out.write("<!-- Calendar -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/fullcalendar.css\">\r\n");
      out.write("<!-- prettyPhoto -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/prettyPhoto.css\">\r\n");
      out.write("<!-- Star rating -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/rateit.css\">\r\n");
      out.write("<!-- Date picker -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(path);
      out.write("/pages/style/bootstrap-datetimepicker.min.css\">\r\n");
      out.write("<!-- CLEditor -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/jquery.cleditor.css\">\r\n");
      out.write("<!-- Uniform -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/uniform.default.css\">\r\n");
      out.write("<!-- Bootstrap toggle -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/bootstrap-switch.css\">\r\n");
      out.write("<!-- Main stylesheet -->\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/pages/style/style2.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Widgets stylesheet -->\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/pages/style/widgets.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 Support for IE -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("\t  <script src=\"js/html5shim.js\"></script>\r\n");
      out.write("\t  <![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(path);
      out.write("/pages/img/favicon/favicon.png\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"load();\">\r\n");
      out.write("\t");

		ArrayList<Conference> list = (ArrayList) request.getSession().getAttribute("list");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"content\">\r\n");
      out.write("\t\t<!-- Main bar -->\r\n");
      out.write("\t\t<div class=\"mainbar\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Page heading -->\r\n");
      out.write("\t\t\t<div class=\"page-head\">\r\n");
      out.write("\t\t\t\t<h2 class=\"pull-left\">\r\n");
      out.write("\t\t\t\t\t<i class=\"icon-table\"></i> 查看会议室\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t<!-- Breadcrumb -->\r\n");
      out.write("\t\t\t\t<div class=\"bread-crumb pull-right\">\r\n");
      out.write("\t\t\t\t\t<a href=\"index.html\"><i class=\"icon-home\"></i> Home</a>\r\n");
      out.write("\t\t\t\t\t<!-- Divider -->\r\n");
      out.write("\t\t\t\t\t<span class=\"divider\">/</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Page heading ends -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Matter -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"matter\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Table -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-head\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pull-left\">查看会议室</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"widget-icons pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"wminimize\"><i class=\"icon-chevron-up\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"wclose\"><i class=\"icon-remove\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table class=\"table table-striped table-bordered table-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>id</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>会议室名称</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>会议室地址</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>是否有多媒体</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>容纳人数</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>会议室状态</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody id=\"all\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												for(Conference person:list){
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(person.getId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(person.getCrmname());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(person.getCrmaddress());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													if(person.getMedia()==1){
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>有</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													}else{
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>无</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													}
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(person.getHoldnum());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													if(person.getCrmstate()==1){
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"/lavaFAQ/pages/user/toAllApply?crmid=");
      out.print(person.getId());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"text-decoration:none;color:blue; \">已有预约</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													}else{
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>空闲</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													}
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												}
											
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"widget-foot\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul id=\"pagination-demo\" class=\"pagination-sm\"></ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Matter ends -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Mainbar ends -->\r\n");
      out.write("\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\">&times;</button>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">修改密码</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">确定删除？</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"updateperson\">提交更改</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.modal-content -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.modal -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Content ends -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer starts -->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<!-- Copyright info -->\r\n");
      out.write("\t\t\t\t\t<p class=\"copy\">\r\n");
      out.write("\t\t\t\t\t\tCopyright &copy; 2018 | <a href=\"#\">fuyu</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer ends -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scroll to top -->\r\n");
      out.write("\t<span class=\"totop\"><a href=\"#\"><i class=\"icon-chevron-up\"></i></a></span>\r\n");
      out.write("\r\n");
      out.write("\t<!-- JS -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.js\"></script>\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/bootstrap.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery-ui-1.9.2.custom.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery UI -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/fullcalendar.min.js\"></script>\r\n");
      out.write("\t<!-- Full Google Calendar - Calendar -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.rateit.min.js\"></script>\r\n");
      out.write("\t<!-- RateIt - Star rating -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.prettyPhoto.js\"></script>\r\n");
      out.write("\t<!-- prettyPhoto -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery Flot -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/excanvas.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.flot.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.flot.resize.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.flot.pie.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.flot.stack.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery Notification - Noty -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.noty.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/themes/default.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/layouts/bottom.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/layouts/topRight.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/layouts/top.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<!-- jQuery Notification ends -->\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/sparklines.js\"></script>\r\n");
      out.write("\t<!-- Sparklines -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.cleditor.min.js\"></script>\r\n");
      out.write("\t<!-- CLEditor -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("\t<!-- Date picker -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.uniform.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery Uniform -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/bootstrap-switch.min.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap Toggle -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/filter.js\"></script>\r\n");
      out.write("\t<!-- Filter for support page -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/custom.js\"></script>\r\n");
      out.write("\t<!-- Custom codes -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/charts.js\"></script>\r\n");
      out.write("\t<!-- Charts & Graphs -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.twbsPagination.js\"\r\n");
      out.write("\t\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/zzsc.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/currency.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" language=\"javascript\">\r\n");
      out.write("\t  function myfun() 　　{ 　　 \r\n");
      out.write("\t\t   var inputValue = document.getElementById(\"to\").value;\r\n");
      out.write("\t       if(inputValue!=null){\r\n");
      out.write("\t    \t   alert(inputValue);\r\n");
      out.write("\t       }\r\n");
      out.write("\t    } 　　\r\n");
      out.write("\t    /*用window.onload调用myfun()*/　\r\n");
      out.write("\t    　\r\n");
      out.write("\t    // 不要括号\r\n");
      out.write("\t    window.onload = myfun;\r\n");
      out.write("\t\tfunction myclick() {\r\n");
      out.write("\t\t\tvar r = confirm(\"确定删除吗?\");\r\n");
      out.write("\t\t\tif (r == true) {\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\talert('呵呵，我失效了吗？');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
