/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-11-29 02:44:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
System.out.println("好的路径:"+path+"/script/jquery-1.9.0.min.js");

      out.write("\n");
      out.write("     \n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\"><head>\n");
      out.write("<title>会议室预约管理系统</title> \n");
      out.write("<meta name=\"keywords\" content=\"fuyu2018\" />\n");
      out.write("<meta name=\"description\" content=\"fuyu2018\" />\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/script/jquery-1.9.0.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/script/login/login.js\"></script>\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/css/login2.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/css/loading.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h1>会议室预约管理系统<sup>V2018</sup></h1>\n");
      out.write("\n");
      out.write("<div class=\"login\" style=\"margin-top:50px;\">\n");
      out.write("    \n");
      out.write("    <div class=\"header\">\n");
      out.write("        <div class=\"switch\" id=\"switch\"><a class=\"switch_btn_focus\" id=\"switch_qlogin\" href=\"javascript:void(0);\" tabindex=\"7\">快速登录</a>\n");
      out.write("\t\t\t<a class=\"switch_btn\" id=\"switch_login\" href=\"javascript:void(0);\" tabindex=\"8\">快速注册</a><div class=\"switch_bottom\" id=\"switch_bottom\" style=\"position: absolute; width: 64px; left: 0px;\"></div>\n");
      out.write("        </div>\n");
      out.write("    </div>    \n");
      out.write("  \n");
      out.write("    \n");
      out.write("    <div class=\"web_qr_login\" id=\"web_qr_login\" style=\"display: block; height: 235px;\">    \n");
      out.write("\n");
      out.write("            <!--登录-->\n");
      out.write("            <div class=\"web_login\" id=\"web_login\">\n");
      out.write("               \n");
      out.write("               \n");
      out.write("               <div class=\"login-box\">\n");
      out.write("    \n");
      out.write("            \n");
      out.write("\t\t\t<div class=\"login_form\">\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(basePath);
      out.write("pages/login/login\" name=\"loginform\" accept-charset=\"utf-8\" id=\"login_form\" class=\"loginForm\" method=\"post\"><input type=\"hidden\" name=\"did\" value=\"0\"/>\n");
      out.write("               <input type=\"hidden\" name=\"to\" value=\"log\"/>\n");
      out.write("               \n");
      out.write("               <div class=\"loginHint\" id=\"loginHint\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\n");
      out.write("                        \n");
      out.write("                <div class=\"uinArea\" id=\"uinArea\">\n");
      out.write("                <label class=\"input-tips\" for=\"u\">帐号：</label>\n");
      out.write("                <div class=\"inputOuter\" id=\"uArea\">\n");
      out.write("                    \n");
      out.write("                    <input type=\"text\" id=\"u\" name=\"mail\" class=\"inputstyle\"/>\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pwdArea\" id=\"pwdArea\">\n");
      out.write("               <label class=\"input-tips\" for=\"p\">密码：</label> \n");
      out.write("               <div class=\"inputOuter\" id=\"pArea\">\n");
      out.write("                    \n");
      out.write("                    <input type=\"password\" id=\"p\" name=\"password\" class=\"inputstyle\"/>\n");
      out.write("                </div>\n");
      out.write("                </div>\n");
      out.write("               \n");
      out.write("                <div style=\"padding-left:50px;margin-top:20px;\"><input type=\"submit\" value=\"登 录\" style=\"width:150px;\" class=\"button_blue\"/></div>\n");
      out.write("              </form>\n");
      out.write("           </div>\n");
      out.write("           \n");
      out.write("            \t</div>\n");
      out.write("               \n");
      out.write("            </div>\n");
      out.write("            <!--登录end-->\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!--注册-->\n");
      out.write("    <div class=\"qlogin\" id=\"qlogin\" style=\"display: none; \">\n");
      out.write("   \n");
      out.write("    <div class=\"web_login\"><form name=\"form2\" id=\"regUser\" accept-charset=\"utf-8\"  action=\"");
      out.print(basePath);
      out.write("login/register\" method=\"post\">\n");
      out.write("\t      <input type=\"hidden\" name=\"to\" value=\"reg\"/>\n");
      out.write("\t\t      \t\t       <input type=\"hidden\" name=\"did\" value=\"0\"/>\n");
      out.write("        <ul class=\"reg_form\" id=\"reg-ul\">\n");
      out.write("        \t\t<div id=\"userCue\" class=\"cue\">快速注册请注意格式</div>\n");
      out.write("                <li>\n");
      out.write("                \t\n");
      out.write("                    <label for=\"user\"  class=\"input-tips2\">用户名：</label>\n");
      out.write("                    <div class=\"inputOuter2\">\n");
      out.write("                        <input type=\"text\" id=\"user\" name=\"user\" maxlength=\"16\" class=\"inputstyle2\"/>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                </li>\n");
      out.write("                \n");
      out.write("                <li>\n");
      out.write("                <label for=\"passwd\" class=\"input-tips2\">密码：</label>\n");
      out.write("                    <div class=\"inputOuter2\">\n");
      out.write("                        <input type=\"password\" id=\"passwd\"  name=\"passwd\" maxlength=\"16\" class=\"inputstyle2\"/>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                <label for=\"passwd2\" class=\"input-tips2\">确认密码：</label>\n");
      out.write("                    <div class=\"inputOuter2\">\n");
      out.write("                        <input type=\"password\" id=\"passwd2\" name=\"\" maxlength=\"16\" class=\"inputstyle2\" />\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                </li>\n");
      out.write("                \n");
      out.write("                <li>\n");
      out.write("                 <label for=\"qq\" class=\"input-tips2\">邮箱：</label>\n");
      out.write("                    <div class=\"inputOuter2\">\n");
      out.write("                       \n");
      out.write("                        <input type=\"text\" id=\"qq\" name=\"qq\" maxlength=\"24\" class=\"inputstyle2\"/>\n");
      out.write("                    </div>\n");
      out.write("                   \n");
      out.write("                </li>\n");
      out.write("                \n");
      out.write("                <li>\n");
      out.write("                    <div class=\"inputArea\">\n");
      out.write("                        <input type=\"button\" id=\"reg\"  style=\"margin-top:10px;margin-left:85px;\" class=\"button_blue\" value=\"注册\"/> <a href=\"#\" class=\"zcxy\" target=\"_blank\">已有账号></a>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                </li><div class=\"cl\"></div>\n");
      out.write("            </ul></form>         \n");
      out.write("      \n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("    \n");
      out.write("    </div>\n");
      out.write("   <!-- loading start -->\n");
      out.write("   <div class=\"spinner\" id=\"loading\">\n");
      out.write("    <div class=\"rect1\"></div>\n");
      out.write("    <div class=\"rect2\"></div>\n");
      out.write("    <div class=\"rect3\"></div>\n");
      out.write("    <div class=\"rect4\"></div>\n");
      out.write("    <div class=\"rect5\"></div>\n");
      out.write("   </div>\n");
      out.write("     <!-- loading end -->\n");
      out.write("    </div>\n");
      out.write("    <!--注册end-->\n");
      out.write("</div>\n");
      out.write("<div class=\"jianyi\">*使用ie8以上版本ie浏览器*本页版权归yufu所有。All Rights Reserved</div>\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
