/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-11-29 02:47:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class widgets1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-cn\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<!-- Title and other stuffs -->\r\n");
      out.write("<title>Bootstrap响应式后台管理系统</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"Bootstrap后台管理系统\" />\r\n");
      out.write("<meta name=\"description\" content=\"Bootstrap后台管理系统\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<!-- Stylesheets -->\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/pages/style/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Font awesome icon -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/font-awesome.css\">\r\n");
      out.write("<!-- jQuery UI -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/jquery-ui.css\">\r\n");
      out.write("<!-- Calendar -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/fullcalendar.css\">\r\n");
      out.write("<!-- prettyPhoto -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/prettyPhoto.css\">\r\n");
      out.write("<!-- Star rating -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/rateit.css\">\r\n");
      out.write("<!-- Date picker -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(path);
      out.write("/pages/style/bootstrap-datetimepicker.min.css\">\r\n");
      out.write("<!-- CLEditor -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/jquery.cleditor.css\">\r\n");
      out.write("<!-- Uniform -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/uniform.default.css\">\r\n");
      out.write("<!-- Bootstrap toggle -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/pages/style/bootstrap-switch.css\">\r\n");
      out.write("<!-- Main stylesheet -->\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/pages/style/style2.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Widgets stylesheet -->\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/pages/style/widgets.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 Support for IE -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("\t  <script src=\"js/html5shim.js\"></script>\r\n");
      out.write("\t  <![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(path);
      out.write("/pages/img/favicon/favicon.png\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Sidebar ends -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Main bar -->\r\n");
      out.write("\t<div class=\"mainbar\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Page heading -->\r\n");
      out.write("\t\t<div class=\"page-head\">\r\n");
      out.write("\t\t\t<h2 class=\"pull-left\">\r\n");
      out.write("\t\t\t\t<i class=\"icon-list-alt\"></i> 首页\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Breadcrumb -->\r\n");
      out.write("\t\t\t<div class=\"bread-crumb pull-right\">\r\n");
      out.write("\t\t\t\t<a href=\"index.html\"><i class=\"icon-home\"></i> Home</a>\r\n");
      out.write("\t\t\t\t<!-- Divider -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Page heading ends -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Matter -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"matter\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Widget -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"widget\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Widget title -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"widget-head\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pull-left\">帮助</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-icons pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"wminimize\"><i class=\"icon-chevron-up\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"wclose\"><i class=\"icon-remove\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"widget-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Widget content -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"padd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"support-faq\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- Lists -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ol id=\"slist\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- List #1 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- Title. Link title is used for filteration. --> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\thref=\"#\">如何使用本系统？</a> <!-- Para -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>您可以使用本系统进行查看会议室状况、查看会议室详细信息、预定会议室等功能</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- List #2 and so on.... -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">菜单？</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>您可以在查看会议室中查看会议室详细内容、在预约管理中进行预约会议室、查看我的预约等信息.</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">申请预约流程？</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>您可以在查看会议室 菜单中查看会议室的状态，如果显示已有预约，可点击查看此会议室所有预约，以便您\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t方便的规划预约时间。在预约管理菜单中点击申请预约，点击申请预约，选择您要\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t预约的会议室。点击表格后面的申请预约按钮。填写申请详细信息（会议主题，开始时间、结束时间 等）即可完成预约</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">审批？</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>您的预约提交后，会由管理员进行审批。管理员同意后，您将收到一封申请成功的邮件。即表示您已预约成功！请在邮件中指定\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t时间到达会议室。您的申请有可能被拒绝哦！您可以在我的预约中查看您所有的预约。在完成会议后，您必须去“我的预约”\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t中点击完成此次预约，这样才能完成此次流程。您也可以删除申请记录。</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Widget footer -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"widget-foot\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>以上内容最终解释权归本人所有.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t            <div class=\"col-md-4\">\r\n");
      out.write("\t\r\n");
      out.write("\t              <!-- Widget -->\r\n");
      out.write("\t              <div class=\"widget\">\r\n");
      out.write("\t                <!-- Widget title -->\r\n");
      out.write("\t                <div class=\"widget-head\">\r\n");
      out.write("\t                  <div class=\"pull-left\">联系我</div>\r\n");
      out.write("\t                  <div class=\"widget-icons pull-right\">\r\n");
      out.write("\t                    <a href=\"#\" class=\"wminimize\"><i class=\"icon-chevron-up\"></i></a> \r\n");
      out.write("\t                    <a href=\"#\" class=\"wclose\"><i class=\"icon-remove\"></i></a>\r\n");
      out.write("\t                  </div>  \r\n");
      out.write("\t                  <div class=\"clearfix\"></div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"widget-content\">\r\n");
      out.write("\t                  <!-- Widget content -->\r\n");
      out.write("\t                  <div class=\"padd\">\r\n");
      out.write("\t                                               <!-- Contact box -->\r\n");
      out.write("\t                             <div class=\"support-contact\">\r\n");
      out.write("\t                                <!-- Phone, email and address with font awesome icon -->\r\n");
      out.write("\t                                <p>您在使用本系统的过程中若遇到bug或其他问题，请联系我.</p>\r\n");
      out.write("\t                                <p><i class=\"icon-phone\"></i> Phone<strong>:</strong> 184-1005-6350</p>\r\n");
      out.write("\t                                <hr />\r\n");
      out.write("\t                                <p><i class=\"icon-envelope-alt\"></i> Email<strong>:</strong> fuyu_hahaha@163.com</p>\r\n");
      out.write("\t                                <hr />\r\n");
      out.write("\t                                <p><i class=\"icon-home\"></i> Address<strong>:</strong> 128, NanZheng Street, FS, Beijing </p>\r\n");
      out.write("\t                                <!-- Button -->\r\n");
      out.write("\t                                <a href=\"#\" class=\"btn btn-default\">Contact Us</a> <a href=\"#\" class=\"btn btn-default\">Check out FAQ</a>\r\n");
      out.write("\t                             </div>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\r\n");
      out.write("\t              </div> \r\n");
      out.write("\t\r\n");
      out.write("\t            </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Recent comments widget -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Server Status -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Matter ends -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Mainbar ends -->\r\n");
      out.write("\t<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer starts -->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<!-- Copyright info -->\r\n");
      out.write("\t\t\t\t\t<p class=\"copy\">\r\n");
      out.write("\t\t\t\t\t\tCopyright &copy; 2012 | <a href=\"#\">Your Site</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer ends -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scroll to top -->\r\n");
      out.write("\t<span class=\"totop\"><a href=\"#\"><i class=\"icon-chevron-up\"></i></a></span>\r\n");
      out.write("\r\n");
      out.write("\t<!-- JS -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.js\"></script>\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/bootstrap.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery-ui-1.9.2.custom.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery UI -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/fullcalendar.min.js\"></script>\r\n");
      out.write("\t<!-- Full Google Calendar - Calendar -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.rateit.min.js\"></script>\r\n");
      out.write("\t<!-- RateIt - Star rating -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.prettyPhoto.js\"></script>\r\n");
      out.write("\t<!-- prettyPhoto -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery Flot -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/excanvas.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.flot.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.flot.resize.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.flot.pie.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.flot.stack.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery Notification - Noty -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.noty.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/themes/default.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/layouts/bottom.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/layouts/topRight.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/layouts/top.js\"></script>\r\n");
      out.write("\t<!-- jQuery Notify -->\r\n");
      out.write("\t<!-- jQuery Notification ends -->\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/sparklines.js\"></script>\r\n");
      out.write("\t<!-- Sparklines -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.cleditor.min.js\"></script>\r\n");
      out.write("\t<!-- CLEditor -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("\t<!-- Date picker -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/jquery.uniform.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery Uniform -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/bootstrap-switch.min.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap Toggle -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/filter.js\"></script>\r\n");
      out.write("\t<!-- Filter for support page -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/custom.js\"></script>\r\n");
      out.write("\t<!-- Custom codes -->\r\n");
      out.write("\t<script src=\"");
      out.print(path);
      out.write("/pages/js/charts.js\"></script>\r\n");
      out.write("\t<!-- Charts & Graphs -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
